#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 150

#define QUICK_TAP_TERM 0

#undef RGB_MATRIX_VAL_STEP
#define RGB_MATRIX_VAL_STEP 24

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "bqbpg/EeaXpQ"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

